export type IndustryLanguage = "es" | "en";

type IndustryCopy = {
  eyebrow: string;
  title: string;
  intro: string;
  badge: string;
  primaryCta: string;
  secondaryCta: string;
  challengeEyebrow: string;
  challengeTitle: string;
  capabilities: Array<{ title: string; text: string; metric: string }>;
  flowEyebrow: string;
  flowTitle: string;
  flow: Array<{ title: string; text: string }>;
  cockpitEyebrow: string;
  cockpitTitle: string;
  cockpitText: string;
  queueTitle: string;
  queue: Array<{ name: string; detail: string; score: string }>;
  resultTitle: string;
  results: string[];
  finalCta: string;
};

export type IndustryData = {
  slug: string;
  image: string;
  secondaryImage: string;
  accent: string;
  accentRgb: string;
  copy: Record<IndustryLanguage, IndustryCopy>;
};

export const industries: Record<string, IndustryData> = {
  "inmobiliaria-construccion": {
    slug: "inmobiliaria-construccion",
    image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1800&q=88",
    secondaryImage: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=84",
    accent: "#22d3ee",
    accentRgb: "34, 211, 238",
    copy: {
      es: {
        eyebrow: "BOTZ PARA INMOBILIARIA Y CONSTRUCCION",
        title: "Tus leads no deberían esperar a que alguien responda.",
        intro: "BOTZ responde, califica, coordina visitas y mantiene tu operación actualizada.",
        badge: "Pipeline inmobiliario activo 24/7",
        primaryCta: "Ver BOTZ trabajando",
        secondaryCta: "Ver el flujo",
        challengeEyebrow: "DE PORTALES A NEGOCIOS REALES",
        challengeTitle: "BOTZ conecta la demanda, los asesores y el inventario en una sola operacion.",
        capabilities: [
          { title: "Captura omnicanal", text: "Centraliza leads de portales, pauta, web, WhatsApp y referidos sin perder contexto.", metric: "100% centralizado" },
          { title: "Calificacion comercial", text: "Identifica compra, arriendo o inversion, presupuesto, zona, plazo y forma de pago.", metric: "Prioridad automatica" },
          { title: "Visitas y seguimiento", text: "Agenda recorridos, asigna asesor, solicita documentos y reactiva interesados.", metric: "Seguimiento 24/7" },
        ],
        flowEyebrow: "FLUJO INMOBILIARIO BOTZ",
        flowTitle: "Del primer mensaje a la visita y el cierre.",
        flow: [
          { title: "Entra el lead", text: "Portal, anuncio, web o WhatsApp." },
          { title: "BOTZ perfila", text: "Interes, presupuesto, zona y urgencia." },
          { title: "Cruza inventario", text: "Propiedades relevantes y disponibilidad." },
          { title: "Activa al asesor", text: "Asignacion, visita y tareas comerciales." },
          { title: "Mueve el negocio", text: "Documentos, negociacion y cierre visible." },
        ],
        cockpitEyebrow: "PROPERTY COMMAND CENTER",
        cockpitTitle: "Inventario y oportunidades avanzando en tiempo real.",
        cockpitText: "El equipo ve quien necesita respuesta, que propiedad interesa y cual es la siguiente accion para mover cada negocio.",
        queueTitle: "Oportunidades prioritarias",
        queue: [
          { name: "Laura M.", detail: "Compra / 2 habitaciones / Toronto", score: "96" },
          { name: "Andres P.", detail: "Inversion / preventa / 30 dias", score: "89" },
          { name: "Camila R.", detail: "Arriendo / visita pendiente", score: "82" },
        ],
        resultTitle: "Menos leads olvidados. Mas visitas con intencion real.",
        results: ["Respuesta inmediata a cada portal", "Asesores enfocados en oportunidades viables", "Inventario recomendado segun perfil", "Pipeline comercial medible de punta a punta"],
        finalCta: "Ver BOTZ con mis propiedades",
      },
      en: {
        eyebrow: "BOTZ FOR REAL ESTATE & CONSTRUCTION",
        title: "Your leads shouldn't have to wait for someone to respond.",
        intro: "BOTZ responds, qualifies, schedules visits and keeps your operation up to date.",
        badge: "Real estate pipeline live 24/7",
        primaryCta: "See BOTZ working",
        secondaryCta: "See the flow",
        challengeEyebrow: "FROM PORTALS TO REAL DEALS",
        challengeTitle: "BOTZ connects demand, advisors and inventory in one operation.",
        capabilities: [
          { title: "Omnichannel capture", text: "Centralize portal, ad, web, WhatsApp and referral leads without losing context.", metric: "100% centralized" },
          { title: "Commercial qualification", text: "Identify purchase, rental or investment, budget, area, timeline and payment method.", metric: "Automatic priority" },
          { title: "Visits and follow-up", text: "Book tours, assign advisors, request documents and reactivate prospects.", metric: "Follow-up 24/7" },
        ],
        flowEyebrow: "BOTZ REAL ESTATE FLOW",
        flowTitle: "From first message to visit and closing.",
        flow: [
          { title: "Lead arrives", text: "Portal, ad, website or WhatsApp." },
          { title: "BOTZ profiles", text: "Interest, budget, area and urgency." },
          { title: "Matches inventory", text: "Relevant properties and availability." },
          { title: "Activates advisor", text: "Assignment, visit and sales tasks." },
          { title: "Moves the deal", text: "Documents, negotiation and visible closing." },
        ],
        cockpitEyebrow: "PROPERTY COMMAND CENTER",
        cockpitTitle: "Inventory and opportunities moving in real time.",
        cockpitText: "Your team sees who needs a response, which property matters and the next action to move every deal.",
        queueTitle: "Priority opportunities",
        queue: [
          { name: "Laura M.", detail: "Buy / 2 bedrooms / Toronto", score: "96" },
          { name: "Andres P.", detail: "Investment / presale / 30 days", score: "89" },
          { name: "Camila R.", detail: "Rental / visit pending", score: "82" },
        ],
        resultTitle: "Fewer forgotten leads. More high-intent visits.",
        results: ["Immediate portal response", "Advisors focused on viable opportunities", "Inventory recommended by profile", "Measurable end-to-end pipeline"],
        finalCta: "See BOTZ with my properties",
      },
    },
  },
  "finanzas-hipotecas-seguros": {
    slug: "finanzas-hipotecas-seguros",
    image: "https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?auto=format&fit=crop&w=1800&q=88",
    secondaryImage: "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?auto=format&fit=crop&w=1200&q=84",
    accent: "#60a5fa",
    accentRgb: "96, 165, 250",
    copy: {
      es: {
        eyebrow: "BOTZ PARA FINANZAS, HIPOTECAS Y SEGUROS",
        title: "Precalifica, documenta y da seguimiento sin friccion.",
        intro: "BOTZ organiza solicitudes, valida informacion y mantiene a clientes y asesores alineados en procesos donde la velocidad y la confianza son decisivas.",
        badge: "Expedientes y seguimiento sincronizados",
        primaryCta: "Ver BOTZ procesar un expediente",
        secondaryCta: "Ver el flujo",
        challengeEyebrow: "MAS CONTROL, MENOS ESPERA",
        challengeTitle: "Una experiencia clara para el cliente y una operacion trazable para el equipo.",
        capabilities: [
          { title: "Precalificacion inteligente", text: "Recopila objetivo, ingresos, perfil, urgencia y condiciones iniciales antes del asesor.", metric: "Perfil completo" },
          { title: "Gestion documental", text: "Solicita, clasifica y controla documentos pendientes con recordatorios automaticos.", metric: "Expediente visible" },
          { title: "Seguimiento y cumplimiento", text: "Registra consentimientos, tareas, hitos y comunicaciones para una trazabilidad consistente.", metric: "Cada paso auditado" },
        ],
        flowEyebrow: "FLUJO FINANCIERO BOTZ",
        flowTitle: "De la consulta a un expediente listo para decision.",
        flow: [
          { title: "Solicitud", text: "Web, WhatsApp, referido o campana." },
          { title: "Perfil inicial", text: "Necesidad, capacidad, plazo y urgencia." },
          { title: "Documentos", text: "Checklist, carga y validacion operativa." },
          { title: "Asignacion", text: "Caso priorizado para el especialista correcto." },
          { title: "Decision y cierre", text: "Seguimiento de hitos y comunicacion activa." },
        ],
        cockpitEyebrow: "FINANCIAL OPERATIONS HUB",
        cockpitTitle: "Cada expediente con estado, responsable y proximo paso.",
        cockpitText: "BOTZ reduce las consultas repetitivas y muestra donde esta cada solicitud, que falta y que casos necesitan atencion.",
        queueTitle: "Casos en revision",
        queue: [
          { name: "Daniel S.", detail: "Hipoteca / documentos completos", score: "93" },
          { name: "Monica A.", detail: "Seguro / cotizacion prioritaria", score: "88" },
          { name: "Jorge C.", detail: "Financiacion / validacion pendiente", score: "79" },
        ],
        resultTitle: "Procesos mas rapidos sin perder control ni confianza.",
        results: ["Precalificacion antes del contacto humano", "Menos documentos y tareas pendientes", "Comunicacion automatica en cada hito", "Visibilidad comercial y operativa unificada"],
        finalCta: "Hablar con BOTZ sobre finanzas",
      },
      en: {
        eyebrow: "BOTZ FOR FINANCE, MORTGAGE & INSURANCE",
        title: "Pre-qualify, document and follow up without friction.",
        intro: "BOTZ organizes applications, validates information and keeps clients and advisors aligned where speed and trust make the difference.",
        badge: "Files and follow-up synchronized",
        primaryCta: "Design my financial workflow",
        secondaryCta: "See the flow",
        challengeEyebrow: "MORE CONTROL, LESS WAITING",
        challengeTitle: "A clear client experience and a traceable operation for your team.",
        capabilities: [
          { title: "Smart pre-qualification", text: "Collect purpose, income, profile, urgency and initial conditions before an advisor steps in.", metric: "Complete profile" },
          { title: "Document management", text: "Request, classify and track missing documents with automatic reminders.", metric: "Visible file" },
          { title: "Follow-up and compliance", text: "Record consent, tasks, milestones and communications for consistent traceability.", metric: "Every step tracked" },
        ],
        flowEyebrow: "BOTZ FINANCIAL FLOW",
        flowTitle: "From inquiry to a decision-ready file.",
        flow: [
          { title: "Application", text: "Web, WhatsApp, referral or campaign." },
          { title: "Initial profile", text: "Need, capacity, timeline and urgency." },
          { title: "Documents", text: "Checklist, upload and operational validation." },
          { title: "Assignment", text: "Prioritized case for the right specialist." },
          { title: "Decision and close", text: "Milestone tracking and active communication." },
        ],
        cockpitEyebrow: "FINANCIAL OPERATIONS HUB",
        cockpitTitle: "Every file with status, owner and next step.",
        cockpitText: "BOTZ reduces repetitive inquiries and shows where every request stands, what is missing and which cases need attention.",
        queueTitle: "Cases under review",
        queue: [
          { name: "Daniel S.", detail: "Mortgage / documents complete", score: "93" },
          { name: "Monica A.", detail: "Insurance / priority quote", score: "88" },
          { name: "Jorge C.", detail: "Financing / validation pending", score: "79" },
        ],
        resultTitle: "Faster processes without losing control or trust.",
        results: ["Qualification before human contact", "Fewer missing documents and tasks", "Automated milestone communication", "Unified sales and operations visibility"],
        finalCta: "Talk to BOTZ about finance",
      },
    },
  },
  "restaurantes-hospitalidad": {
    slug: "restaurantes-hospitalidad",
    image: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=1800&q=88",
    secondaryImage: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?auto=format&fit=crop&w=1200&q=84",
    accent: "#fb923c",
    accentRgb: "251, 146, 60",
    copy: {
      es: {
        eyebrow: "BOTZ PARA RESTAURANTES Y HOSPITALIDAD",
        title: "De la reserva al regreso del cliente, todo conectado.",
        intro: "Automatiza reservas, consultas, pedidos, reputacion y campanas para que el equipo se concentre en la experiencia mientras RestaurantOS mueve la operacion.",
        badge: "Servicio y demanda en una sola vista",
        primaryCta: "Conocer RestaurantOS",
        secondaryCta: "Ver el flujo",
        challengeEyebrow: "CADA MESA, CADA CLIENTE",
        challengeTitle: "Una operacion que responde, confirma y recupera clientes incluso en las horas mas ocupadas.",
        capabilities: [
          { title: "Reservas y atencion", text: "Responde horarios, disponibilidad, menu, ubicacion y eventos desde WhatsApp y web.", metric: "Atencion 24/7" },
          { title: "Operacion conectada", text: "Confirma reservas y pedidos, notifica cambios y coordina tareas del equipo.", metric: "Menos friccion" },
          { title: "Lealtad y reputacion", text: "Solicita resenas, segmenta clientes y activa campanas de retorno personalizadas.", metric: "Mas recurrencia" },
        ],
        flowEyebrow: "FLUJO RESTAURANTOS",
        flowTitle: "Descubrimiento, visita y retorno en un mismo ciclo.",
        flow: [
          { title: "Cliente pregunta", text: "Google, Instagram, web o WhatsApp." },
          { title: "BOTZ responde", text: "Menu, horarios, reservas y eventos." },
          { title: "Confirma", text: "Mesa, pedido o solicitud especial." },
          { title: "Opera", text: "Alertas y tareas para el equipo correcto." },
          { title: "Hace volver", text: "Resena, oferta y campana de reactivacion." },
        ],
        cockpitEyebrow: "RESTAURANTOS LIVE",
        cockpitTitle: "Demanda, servicio y retorno desde un solo panel.",
        cockpitText: "Visualiza conversaciones, reservas y segmentos de clientes para tomar decisiones antes de que una oportunidad se pierda.",
        queueTitle: "Actividad en vivo",
        queue: [
          { name: "Mesa 12", detail: "Reserva / 4 personas / 8:00 PM", score: "OK" },
          { name: "Evento privado", detail: "Cotizacion / 35 personas", score: "HOT" },
          { name: "Cliente frecuente", detail: "Reactivacion / 42 dias", score: "CRM" },
        ],
        resultTitle: "Mas ocupacion, mejor servicio y clientes que regresan.",
        results: ["Reservas atendidas sin espera", "Menos llamadas y mensajes repetitivos", "Reputacion activada despues de cada visita", "Base de clientes segmentada para crecer"],
        finalCta: "Explorar RestaurantOS",
      },
      en: {
        eyebrow: "BOTZ FOR RESTAURANTS & HOSPITALITY",
        title: "From reservation to return visit, everything connected.",
        intro: "Automate reservations, inquiries, orders, reputation and campaigns so your team can focus on the experience while RestaurantOS moves operations.",
        badge: "Service and demand in one view",
        primaryCta: "Discover RestaurantOS",
        secondaryCta: "See the flow",
        challengeEyebrow: "EVERY TABLE, EVERY GUEST",
        challengeTitle: "An operation that responds, confirms and wins guests back even during peak hours.",
        capabilities: [
          { title: "Reservations and service", text: "Answer hours, availability, menu, location and event questions on WhatsApp and web.", metric: "Service 24/7" },
          { title: "Connected operations", text: "Confirm reservations and orders, notify changes and coordinate team tasks.", metric: "Less friction" },
          { title: "Loyalty and reputation", text: "Request reviews, segment guests and trigger personalized return campaigns.", metric: "More repeat visits" },
        ],
        flowEyebrow: "RESTAURANTOS FLOW",
        flowTitle: "Discovery, visit and return in one cycle.",
        flow: [
          { title: "Guest asks", text: "Google, Instagram, web or WhatsApp." },
          { title: "BOTZ responds", text: "Menu, hours, reservations and events." },
          { title: "Confirms", text: "Table, order or special request." },
          { title: "Operates", text: "Alerts and tasks for the right team." },
          { title: "Brings them back", text: "Review, offer and reactivation campaign." },
        ],
        cockpitEyebrow: "RESTAURANTOS LIVE",
        cockpitTitle: "Demand, service and return from one dashboard.",
        cockpitText: "See conversations, reservations and guest segments to act before an opportunity is lost.",
        queueTitle: "Live activity",
        queue: [
          { name: "Table 12", detail: "Reservation / 4 guests / 8:00 PM", score: "OK" },
          { name: "Private event", detail: "Quote / 35 guests", score: "HOT" },
          { name: "Frequent guest", detail: "Reactivation / 42 days", score: "CRM" },
        ],
        resultTitle: "More occupancy, better service and guests who return.",
        results: ["Reservations handled without waiting", "Fewer repetitive calls and messages", "Reputation activated after each visit", "Segmented guest base built for growth"],
        finalCta: "Explore RestaurantOS",
      },
    },
  },
  "servicios-profesionales-b2b": {
    slug: "servicios-profesionales-b2b",
    image: "https://images.unsplash.com/photo-1600880292203-757bb62b4baf?auto=format&fit=crop&w=1800&q=88",
    secondaryImage: "https://images.unsplash.com/photo-1521737604893-d14cc237f11d?auto=format&fit=crop&w=1200&q=84",
    accent: "#a78bfa",
    accentRgb: "167, 139, 250",
    copy: {
      es: {
        eyebrow: "BOTZ PARA SERVICIOS PROFESIONALES Y B2B",
        title: "Convierte conocimiento experto en una operacion comercial escalable.",
        intro: "Conecta captacion, CRM, propuestas, reuniones y seguimiento para que consultoras y empresas de servicios crezcan sin depender de tareas manuales.",
        badge: "Revenue operations para equipos B2B",
        primaryCta: "Disenar mi motor comercial",
        secondaryCta: "Ver el flujo",
        challengeEyebrow: "DE CONTACTOS A CUENTAS ACTIVAS",
        challengeTitle: "BOTZ organiza relaciones complejas y mantiene cada oportunidad en movimiento.",
        capabilities: [
          { title: "Captura y enriquecimiento", text: "Unifica formularios, LinkedIn, email, eventos y referidos con contexto de empresa.", metric: "Cuenta unificada" },
          { title: "CRM y propuestas", text: "Segmenta por potencial, prepara reuniones y activa cotizaciones y seguimientos.", metric: "Pipeline accionable" },
          { title: "Agentes de ejecucion", text: "Agentes IA responden, investigan, actualizan datos y crean tareas para el equipo.", metric: "Menos trabajo manual" },
        ],
        flowEyebrow: "FLUJO B2B BOTZ",
        flowTitle: "De una senal comercial a una relacion de largo plazo.",
        flow: [
          { title: "Detecta demanda", text: "Web, contenido, eventos y outbound." },
          { title: "Enriquece la cuenta", text: "Empresa, rol, necesidad y contexto." },
          { title: "Califica", text: "Fit, urgencia, valor y decisores." },
          { title: "Orquesta la venta", text: "Reunion, propuesta, tareas y seguimiento." },
          { title: "Expande", text: "Onboarding, servicio, renovacion y upsell." },
        ],
        cockpitEyebrow: "B2B REVENUE DESK",
        cockpitTitle: "Cuentas, oportunidades y proximas acciones en contexto.",
        cockpitText: "El CRM deja de ser un archivo pasivo y se convierte en una capa activa que recomienda y ejecuta el siguiente paso.",
        queueTitle: "Cuentas en movimiento",
        queue: [
          { name: "Northline Group", detail: "Discovery / 3 decisores", score: "92" },
          { name: "Atlas Services", detail: "Propuesta enviada / follow-up", score: "86" },
          { name: "Lumen Partners", detail: "Expansion / nueva unidad", score: "78" },
        ],
        resultTitle: "Mas tiempo para asesorar. Menos tiempo administrando el pipeline.",
        results: ["CRM actualizado automaticamente", "Reuniones preparadas con contexto", "Propuestas y seguimientos sin retrasos", "Visibilidad real de cuentas y revenue"],
        finalCta: "Hablar con BOTZ sobre servicios B2B",
      },
      en: {
        eyebrow: "BOTZ FOR PROFESSIONAL SERVICES & B2B",
        title: "Turn expert knowledge into a scalable commercial operation.",
        intro: "Connect acquisition, CRM, proposals, meetings and follow-up so consulting and service firms grow without relying on manual work.",
        badge: "Revenue operations for B2B teams",
        primaryCta: "Design my revenue engine",
        secondaryCta: "See the flow",
        challengeEyebrow: "FROM CONTACTS TO ACTIVE ACCOUNTS",
        challengeTitle: "BOTZ organizes complex relationships and keeps every opportunity moving.",
        capabilities: [
          { title: "Capture and enrichment", text: "Unify forms, LinkedIn, email, events and referrals with company context.", metric: "Unified account" },
          { title: "CRM and proposals", text: "Segment by potential, prepare meetings and trigger quotes and follow-ups.", metric: "Actionable pipeline" },
          { title: "Execution agents", text: "AI agents respond, research, update data and create tasks for the team.", metric: "Less manual work" },
        ],
        flowEyebrow: "BOTZ B2B FLOW",
        flowTitle: "From a commercial signal to a long-term relationship.",
        flow: [
          { title: "Detect demand", text: "Web, content, events and outbound." },
          { title: "Enrich account", text: "Company, role, need and context." },
          { title: "Qualify", text: "Fit, urgency, value and stakeholders." },
          { title: "Orchestrate sale", text: "Meeting, proposal, tasks and follow-up." },
          { title: "Expand", text: "Onboarding, service, renewal and upsell." },
        ],
        cockpitEyebrow: "B2B REVENUE DESK",
        cockpitTitle: "Accounts, opportunities and next actions in context.",
        cockpitText: "CRM stops being a passive archive and becomes an active layer that recommends and executes the next step.",
        queueTitle: "Accounts in motion",
        queue: [
          { name: "Northline Group", detail: "Discovery / 3 stakeholders", score: "92" },
          { name: "Atlas Services", detail: "Proposal sent / follow-up", score: "86" },
          { name: "Lumen Partners", detail: "Expansion / new business unit", score: "78" },
        ],
        resultTitle: "More time advising. Less time managing the pipeline.",
        results: ["CRM updated automatically", "Meetings prepared with context", "Proposals and follow-ups on time", "Real account and revenue visibility"],
        finalCta: "Talk to BOTZ about B2B services",
      },
    },
  },
  "salud-bienestar": {
    slug: "salud-bienestar",
    image: "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&w=1800&q=88",
    secondaryImage: "https://images.unsplash.com/photo-1538108149393-fbbd81895907?auto=format&fit=crop&w=1200&q=84",
    accent: "#2dd4bf",
    accentRgb: "45, 212, 191",
    copy: {
      es: {
        eyebrow: "BOTZ PARA SALUD Y BIENESTAR",
        title: "Una experiencia de atencion clara antes y despues de cada cita.",
        intro: "Automatiza orientacion administrativa, agenda, formularios, recordatorios y reactivacion sin reemplazar el criterio clinico ni perder el trato humano.",
        badge: "Coordinacion administrativa 24/7",
        primaryCta: "Disenar mi flujo de atencion",
        secondaryCta: "Ver el flujo",
        challengeEyebrow: "MENOS FRICCION PARA PACIENTES Y EQUIPOS",
        challengeTitle: "BOTZ coordina la experiencia mientras los profesionales se concentran en atender.",
        capabilities: [
          { title: "Recepcion inteligente", text: "Responde servicios, sedes, horarios, preparacion y preguntas administrativas frecuentes.", metric: "Disponibilidad 24/7" },
          { title: "Agenda y formularios", text: "Coordina citas, confirmaciones, datos previos y documentos requeridos.", metric: "Menos ausencias" },
          { title: "Continuidad de atencion", text: "Activa recordatorios, encuestas, controles administrativos y campanas de reactivacion.", metric: "Mejor continuidad" },
        ],
        flowEyebrow: "FLUJO DE ATENCION BOTZ",
        flowTitle: "De la primera consulta a una experiencia coordinada.",
        flow: [
          { title: "Consulta", text: "Web, directorio, campana o WhatsApp." },
          { title: "Orientacion", text: "Servicio, sede, disponibilidad y requisitos." },
          { title: "Agenda", text: "Cita, confirmacion y datos previos." },
          { title: "Preparacion", text: "Formularios y recordatorios administrativos." },
          { title: "Continuidad", text: "Encuesta, control y reactivacion autorizada." },
        ],
        cockpitEyebrow: "CARE OPERATIONS VIEW",
        cockpitTitle: "Agenda, conversaciones y tareas administrativas alineadas.",
        cockpitText: "El equipo identifica confirmaciones pendientes, consultas sin resolver y acciones necesarias sin revisar multiples sistemas.",
        queueTitle: "Coordinacion del dia",
        queue: [
          { name: "Cita confirmada", detail: "Consulta inicial / 10:30 AM", score: "OK" },
          { name: "Formulario pendiente", detail: "Recordatorio automatico enviado", score: "DOC" },
          { name: "Control administrativo", detail: "Seguimiento / 30 dias", score: "CRM" },
        ],
        resultTitle: "Equipos menos saturados y pacientes mejor orientados.",
        results: ["Respuestas administrativas consistentes", "Mas citas confirmadas y preparadas", "Menos llamadas y tareas repetitivas", "Seguimiento respetuoso y trazable"],
        finalCta: "Hablar con BOTZ sobre salud",
      },
      en: {
        eyebrow: "BOTZ FOR HEALTH & WELLNESS",
        title: "A clear care experience before and after every appointment.",
        intro: "Automate administrative guidance, scheduling, forms, reminders and reactivation without replacing clinical judgment or losing the human touch.",
        badge: "Administrative coordination 24/7",
        primaryCta: "Design my care workflow",
        secondaryCta: "See the flow",
        challengeEyebrow: "LESS FRICTION FOR PATIENTS AND TEAMS",
        challengeTitle: "BOTZ coordinates the experience while professionals focus on care.",
        capabilities: [
          { title: "Smart reception", text: "Answer service, location, hours, preparation and common administrative questions.", metric: "Available 24/7" },
          { title: "Scheduling and forms", text: "Coordinate appointments, confirmations, intake data and required documents.", metric: "Fewer no-shows" },
          { title: "Continuity of care", text: "Trigger reminders, surveys, administrative checks and authorized reactivation campaigns.", metric: "Better continuity" },
        ],
        flowEyebrow: "BOTZ CARE FLOW",
        flowTitle: "From first inquiry to a coordinated experience.",
        flow: [
          { title: "Inquiry", text: "Web, directory, campaign or WhatsApp." },
          { title: "Guidance", text: "Service, location, availability and requirements." },
          { title: "Scheduling", text: "Appointment, confirmation and intake data." },
          { title: "Preparation", text: "Forms and administrative reminders." },
          { title: "Continuity", text: "Survey, check-in and authorized reactivation." },
        ],
        cockpitEyebrow: "CARE OPERATIONS VIEW",
        cockpitTitle: "Schedule, conversations and administrative tasks aligned.",
        cockpitText: "The team spots pending confirmations, unresolved questions and required actions without checking multiple systems.",
        queueTitle: "Today coordination",
        queue: [
          { name: "Appointment confirmed", detail: "Initial consultation / 10:30 AM", score: "OK" },
          { name: "Form pending", detail: "Automatic reminder sent", score: "DOC" },
          { name: "Administrative check", detail: "Follow-up / 30 days", score: "CRM" },
        ],
        resultTitle: "Less overloaded teams and better guided patients.",
        results: ["Consistent administrative answers", "More confirmed and prepared appointments", "Fewer calls and repetitive tasks", "Respectful, traceable follow-up"],
        finalCta: "Talk to BOTZ about health",
      },
    },
  },
  "ecommerce-atencion-cliente": {
    slug: "ecommerce-atencion-cliente",
    image: "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?auto=format&fit=crop&w=1800&q=88",
    secondaryImage: "https://images.unsplash.com/photo-1556740749-887f6717d7e4?auto=format&fit=crop&w=1200&q=84",
    accent: "#38bdf8",
    accentRgb: "56, 189, 248",
    copy: {
      es: {
        eyebrow: "BOTZ PARA E-COMMERCE Y ATENCION AL CLIENTE",
        title: "Cada conversacion puede convertirse en compra y lealtad.",
        intro: "Conecta catalogo, pedidos, soporte, campanas y comportamiento para responder con contexto y activar crecimiento antes y despues de la venta.",
        badge: "Commerce operations en tiempo real",
        primaryCta: "Disenar mi experiencia e-commerce",
        secondaryCta: "Ver el flujo",
        challengeEyebrow: "UNA EXPERIENCIA, TODOS LOS CANALES",
        challengeTitle: "BOTZ une adquisicion, conversion y soporte para que el cliente nunca empiece de cero.",
        capabilities: [
          { title: "Asistencia de compra", text: "Responde sobre productos, disponibilidad, compatibilidad y recomendaciones personalizadas.", metric: "Conversion asistida" },
          { title: "Pedidos y soporte", text: "Consulta estados, cambios, devoluciones y preguntas frecuentes con datos reales.", metric: "Menos tickets" },
          { title: "Growth y retencion", text: "Recupera carritos, segmenta compradores y activa recompra segun comportamiento.", metric: "Mas LTV" },
        ],
        flowEyebrow: "FLUJO COMMERCE BOTZ",
        flowTitle: "De la intencion de compra a una relacion recurrente.",
        flow: [
          { title: "Detecta intencion", text: "Busqueda, anuncio, mensaje o visita." },
          { title: "Recomienda", text: "Producto, variante y respuesta contextual." },
          { title: "Convierte", text: "Carrito, pago y recuperacion automatica." },
          { title: "Acompana", text: "Estado, soporte, cambios y devoluciones." },
          { title: "Reactiva", text: "Segmento, oferta y momento de recompra." },
        ],
        cockpitEyebrow: "COMMERCE CONTROL ROOM",
        cockpitTitle: "Ventas, conversaciones y servicio en una sola senal.",
        cockpitText: "El equipo entiende que quiere el cliente, que ocurrio con su pedido y cual es la accion con mayor probabilidad de conversion.",
        queueTitle: "Senales de compra",
        queue: [
          { name: "Carrito recuperable", detail: "3 productos / alto valor", score: "94" },
          { name: "Consulta de producto", detail: "WhatsApp / disponibilidad", score: "87" },
          { name: "Pedido en seguimiento", detail: "Entrega / actualizacion automatica", score: "OPS" },
        ],
        resultTitle: "Mas conversion sin sacrificar la experiencia del cliente.",
        results: ["Recomendaciones con contexto real", "Carritos recuperados automaticamente", "Soporte conectado al estado del pedido", "Segmentos que impulsan recompra y lealtad"],
        finalCta: "Hablar con BOTZ sobre e-commerce",
      },
      en: {
        eyebrow: "BOTZ FOR E-COMMERCE & CUSTOMER CARE",
        title: "Every conversation can become a purchase and loyalty.",
        intro: "Connect catalog, orders, support, campaigns and behavior to respond with context and trigger growth before and after the sale.",
        badge: "Commerce operations in real time",
        primaryCta: "Design my commerce experience",
        secondaryCta: "See the flow",
        challengeEyebrow: "ONE EXPERIENCE, EVERY CHANNEL",
        challengeTitle: "BOTZ unifies acquisition, conversion and support so customers never start from zero.",
        capabilities: [
          { title: "Shopping assistance", text: "Answer product, availability, compatibility and personalized recommendation questions.", metric: "Assisted conversion" },
          { title: "Orders and support", text: "Check status, changes, returns and common questions using real data.", metric: "Fewer tickets" },
          { title: "Growth and retention", text: "Recover carts, segment buyers and trigger repeat purchases based on behavior.", metric: "Higher LTV" },
        ],
        flowEyebrow: "BOTZ COMMERCE FLOW",
        flowTitle: "From purchase intent to a recurring relationship.",
        flow: [
          { title: "Detect intent", text: "Search, ad, message or visit." },
          { title: "Recommend", text: "Product, variant and contextual answer." },
          { title: "Convert", text: "Cart, payment and automatic recovery." },
          { title: "Support", text: "Status, service, changes and returns." },
          { title: "Reactivate", text: "Segment, offer and repurchase moment." },
        ],
        cockpitEyebrow: "COMMERCE CONTROL ROOM",
        cockpitTitle: "Sales, conversations and service in one signal.",
        cockpitText: "Your team understands what the customer wants, what happened with the order and the action most likely to convert.",
        queueTitle: "Purchase signals",
        queue: [
          { name: "Recoverable cart", detail: "3 products / high value", score: "94" },
          { name: "Product inquiry", detail: "WhatsApp / availability", score: "87" },
          { name: "Order follow-up", detail: "Delivery / automatic update", score: "OPS" },
        ],
        resultTitle: "More conversion without sacrificing customer experience.",
        results: ["Recommendations with real context", "Carts recovered automatically", "Support connected to order status", "Segments that drive repurchase and loyalty"],
        finalCta: "Talk to BOTZ about e-commerce",
      },
    },
  },
};

export const industrySlugs = Object.keys(industries);
