import assert from "node:assert/strict"
import { readFileSync, existsSync } from "node:fs"
import { resolve } from "node:path"

const root = process.cwd()

function read(path) {
  const file = resolve(root, path)
  assert.ok(existsSync(file), `Missing file: ${path}`)
  return readFileSync(file, "utf8")
}

const recommendations = read("app/geo/app/projects/[projectId]/recommendations/page.tsx")
const actionPlan = read("app/api/geo/projects/[projectId]/action-plan/route.ts")
const actionEngine = read("lib/geo/action-engine.ts")
const pipeline = read("lib/geo/pipeline/audit-pipeline.base.ts")
const crawler = read("lib/geo/crawler.ts")
const scoring = read("lib/geo/engines/scoring.ts")
const normalizer = read("lib/geo/engines/normalizer.ts")
const dashboard = read("GEO/app/geo/app/page.tsx")
const auditDetail = read("GEO/components/geo/audit-detail-real.tsx")
const auditsApi = read("app/api/geo/audits/route.ts")
const auditDetailApi = read("app/api/geo/audits/[id]/route.ts")
const promptBuilder = read("lib/geo/pipeline/prompt-builder.ts")
const projectsApi = read("app/api/geo/projects/route.ts")
const promptsLibrary = read("GEO/components/v0/app/geo/app/prompts/page.tsx")
const evidenceRules = read("lib/geo/evidence-rules.ts")
const geoApiAuth = read("lib/geo/api-auth.ts")
const geoAuthDebug = read("app/api/geo/auth-debug/route.ts")
const geoBrowserClient = read("app/geo/supabaseGeoClient.ts")
const geminiProvider = read("lib/geo/engines/providers/gemini.provider.ts")
const perplexityProvider = read("lib/geo/engines/providers/perplexity.provider.ts")
const aiOverviewsProvider = read("lib/geo/engines/providers/ai-overviews.provider.ts")
const usageRepo = read("lib/geo/repositories/usage.repo.ts")

assert.match(recommendations, /DeliverableDrawer/, "Deliverable drawer is missing")
assert.match(recommendations, /downloadMarkdown/, "Markdown export is missing")
assert.match(recommendations, /downloadDeliverablePdf/, "PDF export is missing")
assert.match(recommendations, /detectDeliverableKind/, "Deliverable type detection is missing")
assert.match(recommendations, /landingDeliverable/, "Landing deliverable template is missing")
assert.match(recommendations, /comparisonDeliverable/, "Comparison deliverable template is missing")
assert.match(recommendations, /alternativeDeliverable/, "Alternative deliverable template is missing")
assert.match(recommendations, /contentDeliverable/, "Content deliverable template is missing")
assert.match(recommendations, /faqDeliverable/, "FAQ deliverable template is missing")
assert.match(recommendations, /Evidencia usada|Evidence used/, "Evidence block in drawer is missing")
assert.match(recommendations, /Hay contexto limitado|Limited project context/, "Missing-context warning is missing")
assert.match(recommendations, /localizedGoal/, "Localized goal guard is missing")
assert.match(recommendations, /orderedListMatch/, "PDF ordered-list renderer is missing")
assert.doesNotMatch(recommendations, /BOTZ GEO Deliverable Draft|Borrador de Entregable BOTZ GEO/, "Old PDF header should not be used")
assert.doesNotMatch(recommendations, /Measure and improve/, "English business goal should not leak into Spanish deliverables")

assert.match(actionPlan, /previous_audit/, "Previous audit payload is missing")
assert.match(actionPlan, /crawl_evidence/, "Crawl evidence payload is missing")
assert.match(actionPlan, /evidenceFor/, "Action evidence builder is missing")
assert.match(actionPlan, /isPositiveBrandEvidence/, "Action plan must use shared positive-evidence rules")
assert.match(actionEngine, /aiQueries/, "Action context must load latest AI query evidence")
assert.match(actionPlan, /inferActionCategory/, "Action plan must infer category from real prompt evidence")
assert.match(actionPlan, /agentes de IA para ventas, soporte, WhatsApp y seguimiento de leads/, "Action plan must avoid stale generic industries when AI-agent prompts are present")

assert.match(actionEngine, /previousAuditSnapshot/, "Previous audit comparison helper is missing")
assert.match(actionEngine, /latestCrawlEvidence/, "Latest crawl evidence helper is missing")
assert.match(actionEngine, /crawled_pages/, "Crawled pages query is missing")

assert.match(pipeline, /runCrawlerWithBudget/, "Crawler budget wrapper is missing")
assert.match(pipeline, /persistCrawledPages/, "Crawled pages persistence is missing")
assert.match(pipeline, /crawl_evidence/, "Crawl evidence summary persistence is missing")
assert.match(pipeline, /const crawledPages[\s\S]+const prompts = buildBasePrompts\(context, crawledPages\)/, "Audit prompts must be generated after crawling the site")
assert.match(pipeline, /persistGeneratedPrompts/, "Audit-generated prompts must be persisted to the prompt library")
assert.match(pipeline, /source: "audit_generated"/, "Audit-generated prompts must be traceable in metadata")
assert.match(pipeline, /syncPromptRunResults/, "Audit prompt results must sync back to the prompt library")
assert.match(pipeline, /last_run_results/, "Prompt library must receive audit execution results")
assert.match(pipeline, /fuentes \(externas \)\?confiables/, "Spanish external citation prompts must be classified as citations")
assert.match(pipeline, /compara\|comparar/, "Spanish comparison prompts must be classified as comparisons")
assert.match(pipeline, /assisted/, "Audit pipeline must classify assisted prompts separately from spontaneous visibility")
assert.match(pipeline, /brandMentionedForEvidence/, "Citation prompts must not count brand echoes as evidence")
assert.match(pipeline, /mentionsTargetDomain/, "Citation prompts must mention the target domain before counting positive evidence")
assert.match(pipeline, /no encontr\[eé\]/, "Citation prompts must reject negative no-source answers")

assert.match(crawler, /maxPages = 10/, "Crawler default limit should be 10 pages")
assert.match(crawler, /url\.origin !== origin/, "Crawler same-domain guard is missing")
assert.match(crawler, /AbortController/, "Crawler timeout guard is missing")
assert.match(crawler, /pdf\|png\|jpe\?g/, "Crawler file-type exclusion is missing")

assert.match(scoring, /scoredResults = results\.filter\(\(x\) => x\.mode === "live"\)/, "Scoring must only use live engine results")
assert.match(scoring, /total_results: scoredResults\.length/, "Scoring total_results must count live results only")
assert.match(scoring, /externalUniqueCitations/, "Citation scoring must use external citations for citation prompts")
assert.match(scoring, /mentionsTargetDomain/, "Citation scoring must require the target domain in the answer")
assert.doesNotMatch(dashboard, /prompts_total\) > 0/, "Dashboard must not treat planned prompts as scored evidence")
assert.match(dashboard, /live_ai_queries/, "Dashboard score evidence must require API-confirmed live query counts")
assert.match(auditDetail, /live_ai_queries/, "Audit detail score evidence must require API-confirmed live query counts")
assert.match(auditDetail, /isPositiveBrandEvidence/, "Audit detail must use shared positive-evidence rules")
assert.match(auditsApi, /ai_answers/, "Audits API must verify persisted AI answers")
assert.match(auditsApi, /raw\.mode === "live"/, "Audits API must count only live persisted answers")
assert.match(auditsApi, /isScoreablePrompt/, "Audits API must reject generic prompts as score evidence")
assert.match(auditsApi, /mejores proveedores para e-\?commerce/, "Audits API must exclude generic e-commerce prompts")
assert.match(auditsApi, /geo_prompts/, "Audits API must verify visible prompt records before returning score")
assert.match(auditsApi, /final_score: hasScoreEvidence \? audit\.final_score : null/, "Audits API must hide score without prompt evidence")
assert.match(auditsApi, /liveAiQueries >= 3 && liveEngineCount >= 2/, "Audits API must require sufficient live engine coverage")
assert.match(auditDetailApi, /scoreable_project_prompts/, "Audit detail API must verify prompt-library evidence")
assert.match(auditDetailApi, /final_score: hasScoreEvidence \? audit\.final_score : null/, "Audit detail API must hide score without prompt evidence")
assert.match(auditDetailApi, /liveAiQueries >= 3 && liveEngineCount >= 2/, "Audit detail API must require sufficient live engine coverage")
assert.match(promptBuilder, /isGenericCategory\(cleanGoal\)/, "Audit prompts must reject generic product context")
assert.match(promptBuilder, /return \[\]/, "Audit prompt builder must skip non-scoreable generic prompts")
assert.match(promptBuilder, /buildPageContext/, "Audit prompt builder must use crawled page context")
assert.match(promptBuilder, /removeBrandFromContext/, "Neutral prompt context must remove the brand name")
assert.match(promptBuilder, /WhatsApp conversations and lead follow-up/, "Audit prompts must refine broad AI automation context into concrete use cases")
assert.match(promptBuilder, /Qué plataformas ayudan a equipos B2B/, "Audit prompts must include specific B2B platform discovery prompts")
assert.match(promptBuilder, /scorePageContextSentence/, "Audit prompts must choose page context by product-signal quality")
assert.match(promptBuilder, /Al evaluar/, "Audit prompts must include an assisted validation prompt")
assert.match(promptBuilder, /Exclude the brand's own website/, "Audit citation prompts must request external sources")
assert.match(projectsApi, /isGenericCategory\(cleanGoal\)/, "Initial prompts must reject generic product context")
assert.match(projectsApi, /return \[\]/, "Project creation must skip generic initial prompts")
assert.match(projectsApi, /WhatsApp conversations and lead follow-up/, "Initial prompts must refine broad AI automation context into concrete use cases")
assert.doesNotMatch(projectsApi, /market alternatives" : "alternativas del mercado/, "Initial prompts must not create fake market-alternative prompts without competitors")
assert.match(projectsApi, /Al evaluar/, "Initial prompts must include an assisted validation prompt")
assert.match(projectsApi, /Excluye el sitio propio/, "Initial citation prompts must request external sources")
assert.match(promptsLibrary, /TorontoHispano|side hustles|Canad\[aá\]/, "Prompt library must block obvious non-company false positives")
assert.match(promptsLibrary, /genericTerms/, "Prompt library must filter generic concepts from company mentions")
assert.match(promptsLibrary, /Fuente externa encontrada/, "Prompt library must label citation evidence as external sources")
assert.match(promptsLibrary, /Consulta asistida/, "Prompt library must disclose assisted prompts separately from neutral prompts")
assert.match(promptsLibrary, /menciones del sitio propio se excluyen/, "Prompt library must disclose own-site exclusion for citation prompts")
assert.match(promptsLibrary, /displayMentioned/, "Prompt library must recompute displayed mention status from visible answer evidence")
assert.match(promptsLibrary, /answerContainsTarget/, "Prompt library must require target brand/domain in displayed answer before showing mentioned")
assert.match(promptsLibrary, /answerHasPositiveTargetContext/, "Prompt library must require positive brand context before showing mentioned")
assert.match(promptsLibrary, /isPositiveBrandEvidence/, "Prompt library must use shared positive-evidence rules")
assert.match(promptsLibrary, /alternativas\?\\s\+a/, "Prompt library must reject weak brand references like alternatives to the brand")
assert.match(normalizer, /hasPositiveBrandContext/, "Normalizer must require positive brand context before scoring a brand mention")
assert.match(normalizer, /alternativas\?\\s\+a/, "Normalizer must reject weak brand references like alternatives to the brand")
assert.match(evidenceRules, /isPositiveBrandEvidence/, "Shared evidence rules must expose a single positive-evidence decision")
assert.match(evidenceRules, /answerHasPositiveTargetContext/, "Shared evidence rules must reject weak mention-only contexts")
assert.match(geoApiAuth, /assertSafeGeoWrite/, "GEO API must guard local writes to production Supabase")
assert.match(geoApiAuth, /ALLOW_GEO_PROD_DB_WRITES/, "GEO local production write override must be explicit")
assert.match(geoApiAuth, /Blocked GEO write/, "GEO write guard must fail closed with a clear error")
assert.match(geoApiAuth, /GEO_SUPABASE_URL/, "GEO API must support isolated Supabase URL")
assert.match(geoApiAuth, /GEO_SUPABASE_SERVICE_ROLE_KEY/, "GEO API must support isolated service role key")
assert.match(geoAuthDebug, /GEO_SUPABASE_URL/, "GEO auth debug must validate against isolated Supabase URL")
assert.doesNotMatch(geoAuthDebug, /@\/app\/api\/_utils\/supabase/, "GEO auth debug must not validate against global Supabase URL")
assert.match(geoBrowserClient, /NEXT_PUBLIC_GEO_SUPABASE_URL/, "GEO browser client must support isolated Supabase URL")
assert.match(geoBrowserClient, /NEXT_PUBLIC_GEO_SUPABASE_ANON_KEY/, "GEO browser client must support isolated anon key")
assert.match(geoBrowserClient, /supabaseProjectRef/, "GEO browser auth storage must be scoped by Supabase project")
assert.match(geoBrowserClient, /removeItem\(legacyKey\)/, "GEO browser client must clear legacy auth storage")
assert.match(geminiProvider, /GEO_GEMINI_API_KEY/, "Gemini provider must support GEO-specific local API key")
assert.match(geminiProvider, /legacyProviderApiKey/, "Gemini provider must support legacy GEMINI_PROVIDER-as-key configuration")
assert.match(geminiProvider, /VERTEX_GEMINI_FALLBACK_MODELS/, "Gemini Vertex provider must retry known Vertex model IDs")
assert.match(geminiProvider, /VERTEX_GEMINI_FALLBACK_LOCATIONS/, "Gemini Vertex provider must retry known Vertex locations")
assert.match(geminiProvider, /gemini-2\.5-flash/, "Gemini Vertex provider must default to a verified Vertex model ID")
assert.match(perplexityProvider, /GEO_PERPLEXITY_API_KEY/, "Perplexity provider must support GEO-specific local API key")
assert.match(aiOverviewsProvider, /GEO_SERPAPI_API_KEY/, "AI Overviews provider must support GEO-specific local SerpApi key")
assert.match(usageRepo, /NODE_ENV === "development"/, "GEO usage limits must only be bypassable in local development")
assert.match(usageRepo, /GEO_ENFORCE_DEV_USAGE_LIMITS/, "GEO local usage-limit bypass must be explicitly enforceable for billing tests")
assert.match(usageRepo, /local_development_usage_limit/, "GEO local usage-limit bypass must be traceable in usage metadata")

console.log("GEO smoke checks passed")
