import test from "node:test";
import assert from "node:assert/strict";
import { runAgentTest } from "./agent-test-runtime";
import type {
  AgentModelAdapter,
  AgentModelMessage,
  AgentModelRequest,
  AgentModelTurn,
  AgentToolResultMessage,
  ToolPermissionResolver,
} from "./runtime/types";

const agent = {
  id: "agent-1",
  tenantId: "tenant-1",
  ownerId: "owner-1",
  configuration: { tools: { enabled: [] as string[] } },
};

class QueueModelAdapter implements AgentModelAdapter {
  readonly requests: AgentModelRequest[] = [];
  readonly toolResults: AgentToolResultMessage[] = [];

  constructor(private readonly turns: AgentModelTurn[]) {}

  async generate(request: AgentModelRequest) {
    this.requests.push(request);
    const turn = this.turns.shift();
    if (!turn) throw new Error("No queued model turn");
    return turn;
  }

  appendAssistantTurn(messages: readonly AgentModelMessage[], turn: AgentModelTurn) {
    return [...messages, { role: "assistant" as const, content: turn.text, toolCalls: turn.toolCalls }];
  }

  appendToolResult(messages: readonly AgentModelMessage[], result: AgentToolResultMessage) {
    this.toolResults.push(result);
    return [...messages, {
      role: "tool" as const,
      content: result.content,
      name: result.toolId,
      toolCallId: result.toolCallId,
    }];
  }
}

function permissions(configuration: typeof agent.configuration): ToolPermissionResolver {
  return {
    async resolve(context) {
      assert.equal(context.agentId, agent.id);
      assert.equal(context.tenantId, agent.tenantId);
      assert.equal(context.ownerId, agent.ownerId);
      return {
        agentId: agent.id,
        tenantId: agent.tenantId,
        ownerId: agent.ownerId,
        enabledToolIds: configuration.tools.enabled,
      };
    },
  };
}

function run(modelAdapter: AgentModelAdapter, enabled: string[] = []) {
  return runAgentTest({
    agentId: agent.id,
    tenantId: agent.tenantId,
    ownerId: agent.ownerId,
    actorId: agent.ownerId,
    runId: "test-run",
    systemPrompt: "You are the configured BOTZ agent.",
    message: "Help me",
    conversationHistory: [
      { role: "user", content: "Earlier question" },
      { role: "agent", content: "Earlier answer" },
    ],
    model: "test-model",
    modelAdapter,
    permissionResolver: permissions({ tools: { enabled } }),
    temperature: 0.2,
    maxOutputTokens: 500,
  });
}

test("agent without tools keeps the normal conversation behavior", async () => {
  const model = new QueueModelAdapter([{ text: "Normal answer", toolCalls: [] }]);

  const result = await run(model);

  assert.equal(result.finalText, "Normal answer");
  assert.equal(result.toolCalls, 0);
  assert.deepEqual(model.requests[0].tools, []);
  assert.deepEqual(model.requests[0].messages.map((message) => message.role), [
    "system", "user", "assistant", "user",
  ]);
});

test("agent with generate_pdf can execute it and answer after the tool result", async () => {
  const model = new QueueModelAdapter([{
    text: "",
    toolCalls: [{
      id: "pdf-call",
      toolId: "generate_pdf",
      arguments: {
        template_id: "basic_document",
        data: { title: "Test document", content: "Generated by the configured agent." },
        filename: "test-document.pdf",
      },
    }],
  }, { text: "Your PDF is ready.", toolCalls: [] }]);

  const result = await run(model, ["generate_pdf"]);

  assert.equal(result.finalText, "Your PDF is ready.");
  assert.equal(result.toolCalls, 1);
  assert.deepEqual(model.requests[0].tools.map((tool) => tool.id), ["generate_pdf"]);
  const toolMessage = model.requests[1].messages.find((message) => message.role === "tool");
  assert.ok(toolMessage);
  const toolResult = JSON.parse(toolMessage.content);
  assert.equal(toolResult.ok, true);
  assert.equal(toolResult.data.generated, true);
  assert.equal(toolResult.data.pdfName, "test-document.pdf");
  assert.doesNotMatch(toolMessage.content, /base64|binary/i);
});

test("agent cannot execute generate_pdf when it is not enabled", async () => {
  const model = new QueueModelAdapter([{
    text: "",
    toolCalls: [{
      id: "forbidden-pdf-call",
      toolId: "generate_pdf",
      arguments: {
        template_id: "basic_document",
        data: { title: "Forbidden", content: "This must not be generated." },
      },
    }],
  }, { text: "I cannot generate that document.", toolCalls: [] }]);

  const result = await run(model);

  assert.equal(result.finalText, "I cannot generate that document.");
  assert.deepEqual(model.requests[0].tools, []);
  assert.equal(model.toolResults[0].isError, true);
  assert.match(model.toolResults[0].content, /TOOL_NOT_ALLOWED/);
});
